name: Load Balancer CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3  # Check out the code 

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19' # Specify a Go version

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3 
        with:
          # Optional: Version of golangci-lint
          version: v1.56.2

          # Optional: Configuration file (if not at the root)
          config-file: .golangci.yml 

  build_and_push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: dpuigerarde/hp-lb:latest