name: Load Balancer CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3  # Check out the code 

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19' # Specify a Go version

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3 
        with:
          # Optional: Version of golangci-lint
          version: v1.49 

          # Optional: Configuration file (if not at the root)
          config-file: .golangci.yml 

      # # Other Linters: Example Configurations
      # - name: Run gometalinter (Install and run)
      #   run: |
      #     go install github.com/alecthomas/gometalinter@latest
      #     gometalinter --disable-all --enable=vet --enable=golint ./...  

      # - name: Run go vet (Built-in)
      #   run: go vet ./...